language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - python-numpy
      - python-scipy
      - cython
      - python-dev
      - libblas-dev
      - liblapack-dev
      - gfortran
      - ccache
      - samtools

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install vsearch ; fi

install:
  - "pip install --upgrade pip"
  - "pip install --requirement requirements.txt"
  - "pip install --no-cache-dir --editable ."
  - "python -m Emirge.download bowtie2"
  - "unzip bowtie2*zip"
  - "ln -s bowtie2*/ bowtie2"
script: "PATH=./bowtie2:$PATH nosetests"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache
