language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - python-numpy
      - python-scipy
      - cython
      - python-dev
      - libblas-dev
      - liblapack-dev
      - gfortran
      - ccache

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install vsearch ; fi

install:
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "pip install -e ."
script: nosetests
cache:
  - pip
  - ccache
