language: python
python:
  - "2.7"
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - python-numpy
      - python-scipy
      - cython
      - python-dev
      - libblas-dev
      - liblapack-dev
      - gfortran
      - ccache
install:
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "pip install -e ."
script: nosetests
cache:
  - pip
  - ccache
